spring:
  datasource:
    # 驱动配置信息
    name: mpc #database name
    #   local database
    url: jdbc:mysql://localhost:3306/mpc #local url
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid连接池
    # 连接池配置信息
    druid:
      initial-size: 5 # 初始化连接池大小
      min-idle: 1 # 连接池最小
      max-active: 20 # 连接池最大
      max-wait: 10000 # 获取连接等待超时时间,单位毫秒
      min-evictable-idle-time-millis: 30000 # 一个连接在池中最小生存的时间，单位是毫秒
      time-between-eviction-runs-millis: 60000 # 配置需要多久才进行一次空闲连接检测，检测需要关闭的空闲连接，单位是毫秒

  main:
    banner-mode: "off"

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8008
  #address:  配置127.0.0.1则只能用127.0.0.1访问
  servlet:
    context-path: /v1/mira #所有请求统一url前缀


#log
logging:
  level:
    root: info